[package]
name = "rust_bucket"
version = "0.1.0"
authors = ["Corey McGregor <dormant.aura@gmail.com>"]

[dependencies]
env_logger = "0.5.10"
log = "0.4.0"
rand = "0.5.0"
regex = "0.2.2"
slack = "0.20.0"
